version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: App/Dockerfiles/backend.dockerfile
    container_name: backend_container
    ports:
      - "5000:5000"
  frontend:
    build:
      context: .
      dockerfile: App/Dockerfiles/frontend.dockerfile
    container_name: ui_container
    ports:
      - "80:80"

